# Generated by Django 4.0.7 on 2022-09-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Warehouse Name')),
                ('whtype', models.CharField(choices=[('Frozen', 'Frozen'), ('Cold', 'Cold'), ('Dry', 'Dry'), ('Misc.', 'Misc.')], help_text='describe, is it consider COLD, Misc, Frozen...', max_length=25, verbose_name='Warehouse Type')),
                ('location', models.CharField(blank=True, default='N/A', help_text='describe where it is stack.', max_length=50, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material Name')),
                ('internalName', models.CharField(help_text='i.e (milk, egg, chicken, tuna) in respective unit', max_length=255, verbose_name='Material Internal Name')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Barcode')),
                ('UOP', models.CharField(choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Milligram', 'Milligram'), ('Liter', 'Liter'), ('Pint', 'Pint'), ('Millilitre', 'Millilitre'), ('Tablespoon', 'Tablespoon'), ('Teaspoon', 'Teaspoon'), ('Box', 'Box'), ('Carton', 'Carton'), ('Pcs', 'Pcs'), ('Dozen', 'Dozen'), ('Bottle', 'Bottle')], max_length=25, verbose_name='Unit of Measure Purchase')),
                ('UOC', models.CharField(choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Milligram', 'Milligram'), ('Liter', 'Liter'), ('Pint', 'Pint'), ('Millilitre', 'Millilitre'), ('Tablespoon', 'Tablespoon'), ('Teaspoon', 'Teaspoon'), ('Box', 'Box'), ('Carton', 'Carton'), ('Pcs', 'Pcs'), ('Dozen', 'Dozen'), ('Bottle', 'Bottle')], help_text='note: Unit of consume will be the unit used to store stock and to move inventory', max_length=25, verbose_name='Unit of Measure Consume')),
                ('divisibleUOM', models.DecimalField(decimal_places=2, help_text='For example: Convert from Purchase to Consume unit. In which Unit of Measure material will consume. Further, if bough box of 24pcs, so 24 will be assign here, if consume in box. if each box having item in Kgs, then 24xWeight of each Pcs within carton', max_digits=18)),
                ('type', models.ForeignKey(help_text='for example: Storing Tuna type is Meat, Seafood, and Poultry', on_delete=django.db.models.deletion.DO_NOTHING, to='MM.materialtype', verbose_name='Material Type')),
            ],
            options={
                'unique_together': {('name', 'internalName')},
            },
        ),
    ]
