# Generated by Django 4.0.7 on 2022-10-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmaster',
            name='howMany',
            field=models.DecimalField(decimal_places=4, help_text='Important: If Purchase unit and sale units are not same, than provide unit of consumtion quantity/weights', max_digits=18),
        ),
    ]
