# Generated by Django 4.0.7 on 2022-10-05 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialmaster',
            unique_together={('name', 'internalName'), ('internalName', 'UOC')},
        ),
    ]
