# Generated by Django 4.0 on 2022-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0002_alter_materialmaster_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitemsdet',
            name='iqty',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='grnitemsdet',
            name='irate',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='storedet',
            name='decrease_qty',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='storedet',
            name='increase_qty',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
