# Generated by Django 4.0.7 on 2022-10-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0002_alter_materialmaster_howmany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialmaster',
            old_name='howMany',
            new_name='unitSize',
        ),
    ]
