# Generated by Django 4.0.7 on 2022-10-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0003_alter_grnitemsdet_iqty_alter_grnitemsdet_irate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnnote',
            name='date',
            field=models.DateTimeField(verbose_name='Date of Invoice'),
        ),
    ]
