# Generated by Django 4.0.7 on 2022-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0003_rename_howmany_materialmaster_unitsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitemsdet',
            name='iqty',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='grnitemsdet',
            name='irate',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='packingOf',
            field=models.DecimalField(decimal_places=4, help_text='For example: Convert from Purchase to Consume unit.In which Unit of Measure material will consume. Further, if bough box of 24pcs, so 24 will be assign here, if consume in box. if each box having item in Kgs, then 24xWeight of each Pcs within carton', max_digits=18),
        ),
        migrations.AlterField(
            model_name='storedet',
            name='decrease_qty',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name='storedet',
            name='increase_qty',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
