# Generated by Django 4.0.7 on 2022-10-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0004_alter_grnitemsdet_iqty_alter_grnitemsdet_irate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('ref_doc_no', 'docType')},
        ),
    ]
