# Generated by Django 4.0.7 on 2022-10-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0005_alter_store_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnnote',
            name='isPosted',
            field=models.BooleanField(default=True),
        ),
    ]
