# Generated by Django 4.0.7 on 2022-09-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemprices',
            options={'managed': False, 'verbose_name': 'Menu Item Price', 'verbose_name_plural': 'Menu Items Prices'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'managed': False, 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='numerators',
            options={'managed': False, 'verbose_name': 'Numerator', 'verbose_name_plural': 'Numerator'},
        ),
    ]
